trigger:
  - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: cbnr-devops/AZDO-templates
      endpoint: cbnr-devops

parameters:
  - name: cloud
    displayName: Cloud Provider
    type: string
    default: azure
    values:
      - aws
      - azure

  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - shared
      - staging
      - all

variables:
  basePath: "terraform/${{ parameters.cloud }}/envs"

stages:
  - stage: Checkout
    displayName: Checkout Code
    jobs:
      - job: Checkout
        pool:
          name: "sample-project"
        steps:
          - template: templates/checkout.yml@templates

  - ${{ each item in fromJson('[{"name":"dev","dependsOn":"Checkout"},{"name":"shared","dependsOn":"TerraformApplydev"},{"name":"staging","dependsOn":"TerraformApplyshared"}]') }}:
      - stage: TerraformApply${{ item.name }}
        displayName: Terraform Apply - ${{ upper(item.name) }}
        dependsOn: ${{ item.dependsOn }}
        condition: and(succeeded(), or(eq('${{ parameters.env }}', '${{ item.name }}'), eq('${{ parameters.env }}', 'all')))
        jobs:
          - job: Apply${{ item.name }}
            pool:
              name: "sample-project"
            steps:
              - template: templates/terraform-apply.yml@templates
                parameters:
                  workingDir: $(basePath)/${{ item.name }}
