apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: central-staging-db-credentials
        property: username

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: central-staging-db-credentials
        property: password

    - secretKey: POSTGRES_HOST
      remoteRef:
        key: central-staging-db-credentials
        property: host