apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2        
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa          
            namespace: staging    