apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::987569578177:role/central-dev-irsa-external-secrets-external-secrets