apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
  namespace: dev
spec:
  provider:
    azurekv:
      vaultUrl: https://skssolarsecrets.vault.azure.net/
      authType: ManagedIdentity