apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
  namespace: staging
spec:
  provider:
    azurekv:
      vaultUrl: https://skssecrets.vault.azure.net/
      authType: ManagedIdentity